spring:
  security:
    oauth2:
      client:
        registration:
          okta:
            provider: okta
            client-id: 0oa1atka0oc7wP2Pa4x7
            client-secret:
            client-authentication-method: basic
            authorization-grant-type: authorization_code
            redirect-uri: '{baseUrl}/login/oauth2/code/{registrationId}'
            scope: openid
        provider:
          okta:
            authorization-uri: https://dev-237467.okta.com/oauth2/default/v1/authorize
            token-uri: https://dev-237467.okta.com/oauth2/default/v1/token
            user-name-attribute: sub
            jwk-set-uri: https://dev-237467.okta.com/oauth2/default/v1/keys
      resourceserver:
        jwt:
          issuer-uri: https://dev-237467.okta.com/oauth2/default
          jwk-set-uri: https://dev-237467.okta.com/oauth2/default/v1/keys